In [1]:
import numpy as np
import scipy.special
class Neuralnetwork:
    def __init__(self, inodes, hnodes, onodes, learningrate):
        self.inputnodes= inodes
        self.hiddennodes= hnodes
        self.outputnodes= onodes
        self.lr= learningrate
                  #np.random.normal(mean,SD,size)
        self.wih=np.random.normal(0.0,pow(self.hiddennodes, -0.5),(self.hiddennodes,self.inputnodes))
        self.who=np.random.normal(0.0,pow(self.outputnodes, -0.5),(self.outputnodes, self.hiddennodes))
    
        self.activation=lambda x:scipy.special.expit(x)
   
    def query(self,model_input):
        inputs=np.array(model_input, ndmin=2).T
    #w*x
        hidden_input=np.dot(self.wih, inputs)
    #activation function(w*x)
        hidden_output=self.activation(hidden_input)
    #repeat it for the next layer
        final_input=np.dot(self.who,hidden_output)
        final_output= self.activation(final_input)
        return final_output


In [2]:
input_nodes=3
hidden_nodes=3
output_nodes=3
learningrate=0.3
n=Neuralnetwork(input_nodes,hidden_nodes,output_nodes,learningrate)

#def query(self,model_input)
n.query([1, 0.5, -0.5])



array([[0.54883839],
       [0.46550645],
       [0.44709676]])

In [3]:
import numpy as np
import scipy.special
class Neuralnetwork:
    def __init__(self, inodes, hnodes, onodes, learningrate):
        self.inputnodes= inodes
        self.hiddennodes= hnodes
        self.outputnodes= onodes
        self.lr= learningrate
                  #np.random.normal(mean,SD,size)
        self.wih=np.random.normal(0.0,pow(self.hiddennodes, -0.5),(self.hiddennodes,self.inputnodes))
        self.who=np.random.normal(0.0,pow(self.outputnodes, -0.5),(self.outputnodes, self.hiddennodes))
    
        self.activation=lambda x:scipy.special.expit(x)
    def train(self,model_input, labeled_output):
        inputs=np.array(model_input, ndmin=2).T
        lebelouts=np.array(labeled_output, ndmin=2).T
        
        hidden_input=np.dot(self.wih, hidden_input)
        hidden_output=self.activation(hidden_input)
        
        final_input=np.dot(self.who, hidden_output)
        final_output=self.activation(final_output)
        #error
        output_error=labeledouts-final_output
        hidden_error=np.dot(self.who,output_error)
        

In [4]:
import numpy as np
import scipy.special
class Neuralnetwork:
    def __init__(self,inodes,h1nodes,h2nodes,outnodes,learningrate):
        self.inputnodes=inodes
        self.hidden1nodes=h1nodes
        self.hidden2nodes=h2nodes
        self.outputnodes=onodes
        self.lr=learningrate
        #np.random.normal(mean,SD,size)
        self.wih1=np.random.normal(0.0,pow(hidden1nodes,-0.5),(hidden1nodes,inputnodes))
        self.wh1h2=np.random.normal(0.0,pow(hidden2nodes, -0.5),(hidden2nodes,hidden1nodes))
        self.h2o=np.random.normal(0.0,pow(outputnodes, -0.5),(outputnodes,hidden2nodes))
        #activation function
        self.activation=lambda x:scipy.special.expit(x)
    def train(self,model_input,labeled_output):
        inputs=np.array(model_input, ndmin=2).T
        lebelouts= np.array(labeled_output, ndmin=2).T
        

In [5]:
import numpy as np
np.random.rand(3,2)

array([[0.04582236, 0.10975084],
       [0.1744435 , 0.10122392],
       [0.97318327, 0.44076218]])

In [6]:
a=np.array([2,3,4])
b=np.array([3,4,7])
result1=a+b
result3=np.dot(a,b)
print(result3)
print(result1)

46
[ 5  7 11]


In [7]:
c=np.array([1,2,3])
d=2
result2=c*d
print(result2)

[2 4 6]


In [8]:
A=np.array([[2,3,4],[5,6,7],[1,3,5]])
B=np.array([[3,4,5],[2,6,7],[4,5,6]])
print(A)
print(B)
result=A+B
print(result)

[[2 3 4]
 [5 6 7]
 [1 3 5]]
[[3 4 5]
 [2 6 7]
 [4 5 6]]
[[ 5  7  9]
 [ 7 12 14]
 [ 5  8 11]]


In [10]:
import numpy as np

C = np.array([[1, 7, 8], [4, 5, 6]])
D = np.array([[4, 7, 9], [1, 6, 9], [3, 7, 8]])

# Initialize result with correct dimensions
result = np.zeros((len(C), len(D[0])))

# Perform matrix multiplication
for i in range(len(C)):
    for j in range(len(D[0])):
        for k in range(len(D)):
            result[i][j] += C[i][k] * D[k][j]

print(C)
print(D)
for r in result:
    print(r)


[[1 7 8]
 [4 5 6]]
[[4 7 9]
 [1 6 9]
 [3 7 8]]
[ 35. 105. 136.]
[ 39. 100. 129.]


In [11]:
C=np.array([[1,7,8],[4,5,6],[7,8,9]])
det_C=np.linalg.det(C)
print(det_C)

15.000000000000007


In [12]:
C=np.array([[1,7,8],[4,5,6],[7,8,9]])
print(np.linalg.inv(C))

[[-0.2         0.06666667  0.13333333]
 [ 0.4        -3.13333333  1.73333333]
 [-0.2         2.73333333 -1.53333333]]
