In [1]:
print ('Momina Arshad')

Momina Arshad


In [7]:
#Types of Data
#integer variable
age=22
#string variable
height=5.5
#float Variable
name="Momina"
print (type(x))
print (type(y))
print(type(z))
print("Name:", name)
print("Age:", age)
print("Height:", height)

<class 'int'>
<class 'float'>
<class 'str'>
Name: Momina
Age: 22
Height: 5.5


In [10]:
#Get user input
name= input("enter your name:")
print('Hello', name)

enter your name:momin
Hello momin


In [12]:
#Get user input
name= input("enter your name:")
print(name,"is a student")

momina is a student


In [17]:
num1=2
num2=4
sum= num1+num2
print("The answer is:",sum)


the answer is: 6


In [18]:
num1=3
num2=4
result=num1-num2
result

-1

In [19]:
e=2
t=4
result=e**t
print("The answer is:",result)

The answer is: 16


In [12]:
#List
L=["Hizba","Azka","Momina","Ahmad"]
print (L)
print(type(L))

['Hizba', 'Azka', 'Momina', 'Ahmad']
<class 'list'>


In [13]:
#LENGTH
print(len(L))

4


In [18]:
#FOR ADDING AN ELEMENT IN THE LIST
L.append(2)
print(L)

['Hizba', 'Azka', 'Momina', 'Ahmad', 2, 2, 2, 2]


In [26]:
#dictionary
Dict1={1:"Apple",2:"Banana"}
print("Dictionary", Dict1)

Dictionary {1: 'Apple', 2: 'Banana'}


In [35]:
#Tuple
T=("apple","banana")
print(T)
print(type(T))

('apple', 'banana')
<class 'tuple'>


In [2]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([[3,4,5],[6,7,8]])
print(arr)
print("arrayshape:",arr.shape)
print("size:", arr.size)
print("dimension:", arr.ndim)
print(arr1)
print ("arrayshape:",arr1.shape)
print("arraysize:",arr1.size)
print("dimension:",arr1.ndim)

[1 2 3]
arrayshape: (3,)
size: 3
dimension: 1
[[3 4 5]
 [6 7 8]]
arrayshape: (2, 3)
arraysize: 6
dimension: 2


In [3]:
#Reshaping an array
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1)
a2=a1.reshape(3,3)
print(a2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Reshaping An array
x=np.array([[5,6,3],[4,1,9]])
print(x)
x1=x.reshape(6,)
print(x1)

[[5 6 3]
 [4 1 9]]
[5 6 3 4 1 9]


In [12]:
b=np.array([[2,4,5],[6,7,8]])
print('our array is:',b)
print('the size of array of axis 0:',b.shape[0], '\nsize of array in axis 1:',b.shape[1])
print('our transposed array is:', b.T)
print('the shape is:',b.shape)
print('the size of array in axis 0:',b.T.shape[0], '\nthe size of array in axis 1:',b.T.shape[1])

our array is: [[2 4 5]
 [6 7 8]]
the size of array of axis 0: 2 
size of array in axis 1: 3
our transposed array is: [[2 6]
 [4 7]
 [5 8]]
the shape is: (2, 3)
the size of array in axis 0: 3 
the size of array in axis 1: 2
